name: push

on: [push]

jobs:  
  flake8:
    name: Flake 8 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Pip
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Flake8
      run: |
        flake8 .

  pylint:
    name: Pylint 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Pip
      run: |
        python -m pip install --upgrade pip
        pip install boto3
        pip install pylint

    - name: Pylint
      run: |
        pylint file-dire-set-ops

  bandit:
    name: Bandit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Pip
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Bandit
      run: |
        bandit -r .

  fend:
    name: Fend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: njgibbon/fend@main
